# k8s-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthapp
  template:
    metadata:
      labels:
        app: healthapp
    spec:
      containers:
        - name: healthapp-container
          image: madhu112234/healthprod:latest
          ports:
            - containerPort: 8082
          env:
            - name: PORT
              value: "8082"
---
apiVersion: v1
kind: Service
metadata:
  name: healthapp-service
spec:
  type: NodePort
  selector:
    app: healthapp
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 8082
 
