apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthprod-deployment
  labels:
    app: healthprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthprod
  template:
    metadata:
      labels:
        app: healthprod
    spec:
      containers:
      - name: healthprod-container
        image: madhu112234/healthprod:latest
        ports:
        - containerPort: 8082
        readinessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: 8082
          initialDelaySeconds: 15
          periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: healthprod-service
spec:
  selector:
    app: healthprod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
  type: NodePort
